# Generated by Django 5.2.7 on 2025-12-27 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garage', '0001_initial'),
        ('jobcard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LabourPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour_prices', to='garage.garage')),
                ('labour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='labour.labour')),
                ('vehicle_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labour_prices', to='jobcard.vehiclemodel')),
            ],
            options={
                'unique_together': {('labour', 'garage', 'vehicle_model')},
            },
        ),
    ]
