# Generated by Django 5.2.7 on 2026-04-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labour", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labour",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
