# Generated by Django 5.2.7 on 2025-12-27 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('place', models.CharField(max_length=255)),
                ('logo', models.FileField(blank=True, null=True, upload_to='garage_logos/')),
                ('seal', models.FileField(blank=True, null=True, upload_to='garage_seals/')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='garage.garage')),
            ],
        ),
    ]
