# Generated by Django 5.2.7 on 2026-03-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garage',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
