# Generated by Django 5.2.7 on 2026-03-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_alter_garage_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='place',
        ),
        migrations.RemoveField(
            model_name='garage',
            name='place',
        ),
        migrations.RemoveField(
            model_name='garage',
            name='seal',
        ),
        migrations.AddField(
            model_name='branch',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='garage',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='garage',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
