# Generated by Django 5.2.7 on 2025-12-27 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnumber', models.CharField(max_length=50)),
                ('partname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SparePurchaseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('purchase_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.branch')),
                ('spare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spare.spare')),
            ],
        ),
        migrations.CreateModel(
            name='SpareStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('purchase_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('branches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.branch')),
                ('spare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spare.spare')),
            ],
        ),
    ]
