# Generated by Codex on 2026-05-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spare',
            name='partnumber',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
