# Generated by Django 5.2.7 on 2025-12-27 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobcard', '0001_initial'),
        ('labour', '0001_initial'),
        ('spare', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcardlabour',
            name='labour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labour.labour'),
        ),
        migrations.AddField(
            model_name='jobcardlabour',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user'),
        ),
        migrations.AddField(
            model_name='jobcardspare',
            name='complaints',
            field=models.ManyToManyField(blank=True, related_name='spares', to='jobcard.complaint'),
        ),
        migrations.AddField(
            model_name='jobcardspare',
            name='jobcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spares', to='jobcard.jobcard'),
        ),
        migrations.AddField(
            model_name='jobcardspare',
            name='spare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spare.spare'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobcard.jobstatus'),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='fkMaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='jobcard.vehiclemake'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='vehicle_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobcard.vehiclemodel'),
        ),
        migrations.AlterUniqueTogether(
            name='vehiclemodel',
            unique_together={('name', 'fkMaker')},
        ),
    ]
