# Generated by Django 5.2.7 on 2026-04-25 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobcard", "0003_remove_jobcard_vehicle_model_and_more"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="chassis_number",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="engine_number",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="year",
            field=models.CharField(blank=True, default="", max_length=4),
        ),
        migrations.AlterField(
            model_name="jobcard",
            name="mechanic",
            field=models.ManyToManyField(
                blank=True, related_name="job_mechanic", to="user.user"
            ),
        ),
        migrations.AlterField(
            model_name="jobcard",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="jobcard.vehicle"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vehicle",
            unique_together={("vehicle_number", "user")},
        ),
    ]
