# Generated by Django 5.2.7 on 2026-04-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobcard", "0004_vehicle_chassis_number_vehicle_engine_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobcardlabour",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="jobstatus",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
