# Generated by Django 5.2.7 on 2026-06-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobcard", "0005_jobcardlabour_amount_jobstatus_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobcard",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
